### ISSUE TITLE
Clone Git with Pico

### ISSUE THREAD

**Issue by holmesha** [dr-mod/tiny-system-monitor#1]
How do you clone the Git Repository with a Pico?

**Comment by cdrenteria** [comment]
###  I believe that it says you have to have the pico plugged into another pc then transfer the files manually to the pico while it is plugged in. Included the readme instructions here as well: 

### Installing CircuitPython
1. Download the CircuitPython UF2 from the official website [here](https://circuitpython.org/board/raspberry_pi_pico/).
2. Push and hold the BOOTSEL button and plug your Pico into the USB port of your computer. Release the BOOTSEL button
   after your microcontroller is connected.
3. It will mount as a Mass Storage Device called RPI-RP2.
4. Drag and drop the CircuitPython UF2 file onto the RPI-RP2 volume.

### Software installation
Download and copy the software

```shell
cd ~
git clone https://github.com/dr-mod/tiny-system-monitor.git
cp tiny-system-monitor/src/* <CIRCUITPY DRIVE>
```

**Comment by cdrenteria** [comment]
@dr-mod If the above response is correct would it be alright if I add some clarification to the readme?

**Comment by holmesha** [comment]
You're right, I misunderstood. Clone git to your computer, then copy files over to the pico. I was just unclear on the steps. Thanks!

**Comment by cdrenteria** [comment]
> You're right, I misunderstood. Clone git to your computer, then copy files over to the pico. I was just unclear on the steps. Thanks!

No problem. Let me know when you get it working !

**Comment by dr-mod** [comment]
Hi @cdrenteria , thank you for adding the additional clarification to README! Hope this will help to avoid further confusions.
