### ISSUE TITLE
Incomplete Description / Code?

### ISSUE THREAD

**Issue by r0oland** [dr-mod/tiny-system-monitor#3]
I might just be to silly to understand, but could it be that you are only showing half of what is needed here?

I browsed your code to see how you are actually getting the system load and other info via USB but all you do is waiting for some data from the pc and then decoding it in lines 242 and following:
```
raw = usb_cdc.data.read(available)
data = struct.unpack("bbbbIIf", raw)
...
```
But where is that data coming from? Or does Circuit Python somehow generate this?

**Comment by dr-mod** [comment]
Hi @r0oland , I've just uploaded a rudimentary daemon for your host system to collect and send the data over to the external monitor. Hope this helps.
